### ISSUE TITLE
Incorrect automerge resolution

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1102] opened 2016-08-12 15:01 UTC
Automerge sometimes resolves patches to the wrong values. Specifically, we changed the value of a pointer and then a minute later it was set to the previous value...

Screenshots of the history (maybe can be helpful):
<img width="1805" alt="screen shot 2016-08-12 at 9 47 34 am" src="https://cloud.githubusercontent.com/assets/4982789/17626549/44dcc1b6-6073-11e6-98d0-80392d7f3f64.png">
<img width="1822" alt="screen shot 2016-08-12 at 9 42 24 am" src="https://cloud.githubusercontent.com/assets/4982789/17626551/44de0f58-6073-11e6-96bc-cb10529d78a8.png">
<img width="1851" alt="screen shot 2016-08-12 at 9 42 07 am" src="https://cloud.githubusercontent.com/assets/4982789/17626550/44dd3f7e-6073-11e6-966f-4a16f7dfbe41.png">

**Comment by pmeijer** [comment] 2016-08-17 14:38
You wouldn't happen to have access to the two merged (models at the) commits?

How are you handling merged commits in the plugin (if it does multiple saves)?

**Comment by brollb** [comment] 2016-08-17 14:45
I am not doing much as far as handling merged commits... Should I be reloading the root node and cached nodes in the plugin?

**Comment by pmeijer** [comment] 2016-08-17 14:52
Yes, otherwise your core will be in the old state w/o the pointer. When making a new commit the diff with the head of branch and that commit will contain the indented changes plus the removal of the pointer.

**Comment by pmeijer** [comment] 2016-08-17 14:53
https://github.com/webgme/webgme/blob/master/src/plugin/PluginBase.js#L462-L463

**Comment by kecso** [comment] 2016-08-17 14:53
From the logs and the reproduction of the use case it seems that the AM itself is successful and correct, but the plugin needs to refresh its cached nodes after every save to make it sure that it doesn't overwrite something that has been changed in the meantime.

**Comment by pmeijer** [comment] 2016-08-17 15:10
Actually it doesn't have to fast-forward in the sense of calling this(plugin).fastForward - but the key is to make sure that the core (rootHash) is in sync with the merged commit.

**Comment by brollb** [comment] 2016-08-17 15:24
what do you mean by "make sure it is in sync"? I understand updating the nodes in the cache and `this.rootNode` but do I need to do anything special w/ the core (such as instantiate a new `core` object?)

**Comment by pmeijer** [comment] 2016-08-17 15:30
Yeah sorry if that was vague.. By in sync I meant that the self.current(commit)Hash of the plugin should point to the commit with the rootHash corresponding to `this.rootNode`. When a commit is merged the current(commit)Hash is updated, but the rootNode and all cached nodes aren't automatically so.

**Comment by kecso** [comment] 2016-08-18 17:19
Closing the issue as there is no actual problem with the auto-merge functionality.
The main outcome of the issue is that the plugin is responsible to update its memory content so it does not override any merge result by using old data.

**Closed by kecso** 2016-08-18 17:19 UTC
Labels: Bug, Major
