### ISSUE TITLE
Abstract models cannot be moved.

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme#629] opened 2015-10-12 15:41 UTC
I am trying to place all my metamodels inside the Language meta object. 
But I am not able to place the "Port" FCO inside this, but everything else.

Note the only thing about this "Port" is that it is abstract. Is this what is causing it to exhibit this behavior?

http://editor.webgme.org/?project=demo%2Byog_test1&branch=master&node=%2F2008328440&visualizer=ModelEditor&tab=0

Also surprisingly if I make it non-abstract I am able to move the "Port" FCO to the "Language" composition.

Is this expected behavior?

**Comment by pmeijer** [comment] 2015-10-12 16:24
Not being able to move or delete the FCO node from the root-node is by design - so that is the correct behavior.

About moving an abstract node - I think this is prohibited by the rule that abstract nodes cannot be instantiated and it "spills" over to the move. For now you will need to make it non-abstract before moving it.

**Comment by pmeijer** [comment] 2015-12-15 23:24
While working with the meta-nodes, make them non-abstract.

**Closed by pmeijer** 2015-12-15 23:24 UTC
Labels: ready
