### ISSUE TITLE
Repositioning a child of an instance throws an error

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#443] opened 2015-07-11 19:19 UTC
Repositioning a child of an instance throws an error and the new position of the object is not commited; however, UI behaves like everything worked correctly. The UI stays 'In Sync' and 'Connected', and seems like the object is updated to its new position. Refreshing the page reveals that the updates on the objects were vain.

The case can be reproduced with the following project.
https://drive.google.com/file/d/0B6icounl9q69Yk9CYUNEN3l0QTQ/view?usp=sharing

* Go to ROOT > projects > A-instance
* Move a 'functions' object

Attributes cannot be updated as well.
```
Throwing Error: ASSERT failed
    at assert (http://localhost:8888/common/util/assert.js:14:25)
    at mutate (http://localhost:8888/common/core/coretree.js:503:17)
    at mutate (http://localhost:8888/common/core/coretree.js:483:42)
    at Object.setProperty (http://localhost:8888/common/core/coretree.js:597:18)
    at Object.setRegistry (http://localhost:8888/common/core/corerel.js:123:22)
    at Client.setRegistry (http://localhost:8888/js/client/gmeNodeSetter.js:28:28)
    at ModelEditorControlDiagramDesignerWidgetEventHandlers._saveReposition (http://localhost:8888/js/Panels/ModelEditor/ModelEditorControl.DiagramDesignerWidgetEventHandlers.js:739:24)
    at http://localhost:8888/js/Panels/ModelEditor/ModelEditorControl.DiagramDesignerWidgetEventHandlers.js:715:22
Uncaught Error: ASSERT failed
```

**Comment by kecso** [comment] 2015-07-14 14:19
could you please try with re-importing the project you attached?
I cannot reproduce it, so I am wondering if it has something to do with the actual state of the database on your machine

**Comment by hakantunc** [comment] 2015-07-14 14:36
You're right. Only the original project throws this error. I couldn't reproduce it with importing.

**Comment by kecso** [comment] 2015-07-14 14:45
so could you provide a db dump, or can I close the issue?

**Closed** 2015-07-14 19:40 UTC
Labels: Breaking change, Bug, Core, Major
